---
title: "R Notebook"
output: html_notebook
---

```{r}

# packages required:

library(tidyverse)
library(here)

```
1. read in data

```{r}
# read in data
decathlon <- read_csv("../clean_data/decathlon_clean.csv")
```

2. Who had the longest long jump seen in the data?

```{r}
longest_jump <- decathlon %>% 
  select(names, long_jump) %>% 
  arrange(desc(long_jump)) %>% 
  head()
longest_jump

# Clay had the longest jump (7.96).
```

3.What was the average 100m time in each competition?

```{r}
avg_100m <- decathlon %>% 
  select(short_run, competition_name) %>% 
  group_by(competition_name) %>% 
  summarise(avg_short_run = mean(short_run))

avg_100m
```


4. Who had the highest total points across both competitions?

```{r}
highest_total_score <- decathlon %>%
  select(names, points, competition_name) %>% 
  group_by(names) %>% 
  summarise(final_score = sum(points)) %>% 
  arrange(desc(final_score)) %>% 
  head(n = 1)
  
highest_total_score
  
```

5. What was the shot-put scores for the top three competitors in each competition?

```{r}
shot_put_best <- decathlon %>% 
  select(names, shot_put, competition_name) %>% 
  group_by(competition_name)%>% 
  arrange(desc(shot_put)) %>%
  slice_max(shot_put, n = 3)
 
shot_put_best
```

6. What was the average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds?


```{r}

avg_points_longrun <- decathlon %>% 
  select(long_run, points) %>% 
  mutate(above_50 = if_else(long_run > 50, TRUE, FALSE)) %>% 
  group_by(above_50) %>% 
  summarise(average_points = mean(points))

avg_points_longrun
```